//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGDFiteness4.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string Image { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> Instock { get; set; }

        public virtual CategoryTBL CategoryTBL { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
